get:
  tags: ["Base"]
  description: List all Base entries
  operationId: listBase
  parameters:
    - in: query
      type: string
      name: format
      enum: [json, xml, yaml]
      default: json
  responses:
    200:
      description: '200 / OK'
      schema:
        type: array
        items:
          $ref: '#/definitions/Base'
post:
  tags: ["Base"]
  description: Create new Base entry
  operationId: createBase
  security:
    - OauthSecurity: [admin]
  parameters: 
    - in: query
      type: string
      name: format
      enum: [json, xml, yaml]
      default: json       
    - in: body
      name: body
      description: Base
      required: true
      schema:
        $ref: '#/definitions/Base'
  responses:
    200:
      description: '200 / OK'
      schema:
        $ref: '#/definitions/Base'