swagger: "2.0"
info:
  description: "Xegony API"
  version: "1.0.0"
  title: "Xegony API"
  contact:
    email: "rebuildeq@gmail.com"  
host: "localhost:8080/api/"
produces:
  - application/json
  - application/xml
  - application/yaml
paths:
  /account:
    $ref: 'account.yaml'
  /account/{accountId}:
    $ref: 'account-by-id.yaml'    
  /activity:
    $ref: 'activity.yaml'
  /activity/{activityId}:
    $ref: 'activity-by-id.yaml'
  /base:
    $ref: 'base.yaml'
  /base/{class}/{level}:
    $ref: 'base-by-id.yaml'
  /bazaar:
    $ref: 'bazaar.yaml'
  /bazaar/{class}/{level}:
    $ref: 'bazaar-by-id.yaml'
  /character:
    $ref: 'character.yaml'    
  /character/{characterId}:
    $ref: 'character-by-id.yaml'  
  /faction:
    $ref: 'faction.yaml'    
  /faction/{factionId}:
    $ref: 'faction-by-id.yaml'
  /goal:
    $ref: 'goal.yaml'    
  /goal/{goalId}:
    $ref: 'goal-by-id.yaml'  
  /item:
    $ref: 'item.yaml'    
  /item/{itemId}:
    $ref: 'item-by-id.yaml'  
  /login:
    $ref: 'login.yaml'    
  /lootdrop:
    $ref: 'lootdrop.yaml'    
  /lootdrop/{lootDropId}:
    $ref: 'lootdrop-by-id.yaml'  
  /lootdropentry:
    $ref: 'lootdropentry.yaml'    
  /lootdropentry/{lootDropEntryId}:
    $ref: 'lootdropentry-by-id.yaml'  
  /loottable:
    $ref: 'loottable.yaml'    
  /loottable/{lootTableId}:
    $ref: 'loottable-by-id.yaml' 
  /loottableentry:
    $ref: 'loottableentry.yaml'    
  /loottableentry/{lootTableEntryId}:
    $ref: 'loottableentry-by-id.yaml' 
  /npc:
    $ref: 'npc.yaml'    
  /npc/{npcId}:
    $ref: 'npc-by-id.yaml' 
  /npcloot:
    $ref: 'npcloot.yaml'    
  /npcloot/{npcLootId}:
    $ref: 'npcloot-by-id.yaml' 
  /post:
    $ref: 'post.yaml'    
  /post/{postId}:
    $ref: 'post-by-id.yaml' 
  /task:
    $ref: 'task.yaml'    
  /task/{taskId}:
    $ref: 'task-by-id.yaml' 
  /topic:
    $ref: 'topic.yaml'    
  /topic/{topicId}:
    $ref: 'topic-by-id.yaml' 
  /user:
    $ref: 'user.yaml'    
  /user/{userId}:
    $ref: 'user-by-id.yaml' 
  /zone:
    $ref: 'zone.yaml'    
  /zone/{zoneId}:
    $ref: 'zone-by-id.yaml' 
definitions:
  Account:
    type: object
    $ref: '../definitions/account.yaml'
  Activity:
    type: object
    $ref: '../definitions/activity.yaml'
  Base:
    type: object
    $ref: '../definitions/base.yaml'
  Bazaar:
    type: object
    $ref: '../definitions/bazaar.yaml'
  Character:
    type: object
    $ref: '../definitions/character.yaml'
  Faction:
    type: object
    $ref: '../definitions/faction.yaml'  
  Item:
    type: object
    $ref: '../definitions/item.yaml'  
  LootDrop:
    type: object
    $ref: '../definitions/lootdrop.yaml'  
  LootDropEntry:
    type: object
    $ref: '../definitions/lootdropentry.yaml'  
  LootTable:
    type: object
    $ref: '../definitions/loottable.yaml'  
  LootTableEntry:
    type: object
    $ref: '../definitions/loottableentry.yaml' 
  Npc:
    type: object
    $ref: '../definitions/npc.yaml'  
  NpcLoot:
    type: object
    $ref: '../definitions/npcloot.yaml'  
  Post:
    type: object
    $ref: '../definitions/post.yaml'
  Task:
    type: object
    $ref: '../definitions/task.yaml'
  Topic:
    type: object
    $ref: '../definitions/topic.yaml'  
  User:
    type: object
    $ref: '../definitions/user.yaml' 
  Zone:
    type: object
    $ref: '../definitions/zone.yaml'
  LoginRequest:
    type: object      
    $ref: '../definitions/loginrequest.yaml'
securityDefinitions:
  ApiKey:
    type: apiKey
    name: Authorization
    in: header
  OauthSecurity:
    type: oauth2
    flow: accessCode
    authorizationUrl: 'http://localhost/authorization'
    tokenUrl: 'http://localhost/token'
    scopes:
      admin: Administrator
      moderator: Moderator scope
      owner: Owner scope
  Session:
    type: apiKey
    name: session
    in: query
externalDocs:
  description: "Find out more about Xegony"
  url: "github.com/xackery/xegony"